### ISSUE TITLE
Convert to Current Swift Syntax?

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#1]
I simply clicked "Convert". I'm not too sure, though, if there are any adverse side-effects by doing this. Hopefully, there are none.

<img width="420" alt="screen shot 2016-09-29 at 10 18 04 am" src="https://cloud.githubusercontent.com/assets/344066/18938889/a093d978-862e-11e6-87a4-fa9f2fafcc28.png">

**Comment by masarapmabuhay** [comment]
Upon converting to Swift 3, I received 2 issues in SWXMLHash iOS Tests, related to a Dependency Analysis Error: 
1) Signing for "SWXMLHash iOS Tests" requires a development team. Select a development team in the project editor. Code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 10.0'
2) Signing for "SWXMLHash iOS Tests" requires a development team. Select a development team in the project editor. Code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 10.0'

**Comment by chrisamanse** [comment]
Thanks for reporting this issue, @masarapmabuhay.

Currently, we only support Xcode 7 (which uses Swift 2.2). It's indicated in the [setup part](https://github.com/chrisamanse/LIKHA-Guide/blob/master/README.md#setup) of the guide. When opening the project using Xcode 7.3.1, the Convert to Current Swift syntax won't show up, and the project will work fine.

**Comment by masarapmabuhay** [comment]
Thank you for the reply @chrisamanse.

In that case, I ought not to convert the code to Swift 3 then.

Merci beaucoup!
Mike
