### ISSUE TITLE
Cover Image short even if 600x850

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#10]
Salut! I made a 600x850 .jpg image, just like in the sample cover image in the guide. Unfortunately, it seems that the image I made is still short when I ran the simulator.

<img width="310" alt="screen shot 2016-10-12 at 5 30 28 pm" src="https://cloud.githubusercontent.com/assets/344066/19305013/9f79d89e-90a1-11e6-814c-f0d566b75cfb.png">

Any ideas why this may be so?

Merci!

**Comment by chrisamanse** [comment]
I assume by short you mean that the START button is not all the way at the bottom?

If so, this is by design, because the Cover Image can either be short or very long, but it will always fit to the width of the device. If it's short, then the START button will be just below the Cover Image (specifically, the Cover Image and START button has an 8pt gap between them constantly), and it will have noticeable space at the bottom. If it's long, then the START button will also be just below the Cover Image, and if it doesn't fit in the screen (Cover Image has a taller height than the device), then the start page will become scrollable.

**Comment by masarapmabuhay** [comment]
Merci beaucoup pour ta réponse! What I meant was, even if I put a cover image, the default background image is still visible. Is there a way to put the start button above the cover image?

**Comment by masarapmabuhay** [comment]
p.s. By "above" I mean, on top of the cover image?

**Comment by chrisamanse** [comment]
I believe you want this to be the cover image:

![screen shot 2016-10-12 at 03 26 04](https://cloud.githubusercontent.com/assets/12277586/19306681/aa46b7f4-902b-11e6-8187-45c54d27fd60.png)

And the image behind it to be the background image:

![screen shot 2016-10-12 at 03 26 53](https://cloud.githubusercontent.com/assets/12277586/19306710/cb4ea75e-902b-11e6-8bd1-141e4076d160.png)

If so, don't manually merge the Cover Image and background image into one image file. There's `Cover` for the cover image, and `BG` for background image, simply replace them, then the START button will be on top of the background image (by means of depth, or z-axis), and below (y-axis) the cover image:

![screen shot 2016-10-12 at 03 30 57](https://cloud.githubusercontent.com/assets/12277586/19306823/580fe540-902c-11e6-9378-a915ea6daf63.png)

Then, this will be your output (different images used, BG taken from Sunshine, and Cover from Dahon FI):

• In Xcode (highlighted which ones to change):
![screen shot 2016-10-12 at 03 33 26](https://cloud.githubusercontent.com/assets/12277586/19307005/2c7dc9c8-902d-11e6-8feb-f5cab2271b70.png)

• Device output:
![screen shot 2016-10-12 at 03 37 30](https://cloud.githubusercontent.com/assets/12277586/19307059/6381c83e-902d-11e6-9099-b00b6968b64c.png)

**Comment by masarapmabuhay** [comment]
Yes, you got it! That is exactly what I want! It's almost like what I do using UsbongKit (Android). Merci beaucoup!

**Comment by masarapmabuhay** [comment]
Salut! I did what you instructed, and this is what I got:
<img width="312" alt="screen shot 2016-10-13 at 4 01 57 pm" src="https://cloud.githubusercontent.com/assets/344066/19341140/c9dc7c14-915e-11e6-9166-33f9c05b5b34.png">

There is no space above the cover image. I then added a transparent space above the cover image, and exported it as .png. If I exported it as .jpg, the transparent space will not be transparent.
<img width="310" alt="screen shot 2016-10-13 at 4 08 57 pm" src="https://cloud.githubusercontent.com/assets/344066/19341587/921564d8-9160-11e6-9d08-1b6d4f79b8ff.png">

May I know if I really have to add the transparent space, or am I missing a step?

Merci beaucoup!

**Comment by chrisamanse** [comment]
Yes, we have to add the transparent space in the image if we want to have a space at the top/bottom. If you have further knowledge of using constraints in iOS, you can do this by changing the constant of the top or bottom constraint of the cover (ex. changing the constant of the top constraint to 10 will make the cover image have 10 pts space at the top).

**Comment by masarapmabuhay** [comment]
D'accord! Je comprends! Merci bien!
