### ISSUE TITLE
When I press Start from the Cover page, the transition animation uses the default BG image 

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#11]
Salut! When I press Start from the Cover page using the simulator, the transition animation (upward motion) uses the default BG image. Is there a way to remove the default BG image, or replace it with another one? Merci beaucoup!

**Comment by chrisamanse** [comment]
Unfortunately, this has to be done in the [UsbongKit](https://github.com/usbong/UsbongKit) framework.

**Comment by masarapmabuhay** [comment]
D'accord! Merci beaucoup!
