### ISSUE TITLE
HTML tags unrecognized in UsbongKit (iOS)

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#12]
Salut! I'm now checking my .utree content using the Simulator, and I noticed that HTML tags are not yet recognized by UsbongKit (iOS). 

<img width="314" alt="screen shot 2016-10-15 at 2 27 02 pm" src="https://cloud.githubusercontent.com/assets/344066/19407968/dd05627a-92e3-11e6-9ec3-dc4f023f4d37.png">

I can remove the tags, but that would mean I'll have to modify the .utree file, which already works on UsbongKit (Android). Perhaps, you can recommend another workaround?

Merci beaucoup!

**Comment by chrisamanse** [comment]
Hi @masarapmabuhay, this is not yet implemented in UsbongKit iOS. However, the line break tag is supported, which is the only tag supported in iOS. I'll transfer this issue to [UsbongKit](https://github.com/usbong/UsbongKit).

**Comment by chrisamanse** [comment]
Unfortunately, there is no possible workaround for this.

**Comment by masarapmabuhay** [comment]
D'accord! Perhaps later on, I'll be able to learn Swift and come up with a fix. In the meantime, I'm focusing on the LIKHA-Guide. Merci beaucoup!
