### ISSUE TITLE
Tool to take screenshots of the app for the App Store

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#16]
Salut! I remember you use a tool to take screenshots of iOS apps for use in the App Store. May I know what it is? Perhaps we can share it in the LIKHA-Guide as well? Merci bien!

**Comment by chrisamanse** [comment]
The tool is called [fastlane](https://github.com/fastlane/fastlane) (specifically, snapshot). I omitted this part as it requires use of the Terminal, which might complicate the guide and make it not beginner-friendly.

**Comment by masarapmabuhay** [comment]
D'accord! Merci bien!
