### ISSUE TITLE
Japanese and Mandarin still have to be unlocked

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#17]
Salut! I was able to quickly build an app using the LIKHA-Guide and the .utree of the "Missing Pieces Become the Big O", and was testing it via the Simulator, when I noticed that the Japanese and Mandarin languages still need to be unlocked. Spanish, Ilonggo, Filipino, and English, however, are all accessible already.

<img width="376" alt="screen shot 2016-11-03 at 7 10 02 pm" src="https://cloud.githubusercontent.com/assets/344066/19963879/8c0736d0-a1f9-11e6-9893-d3024b7cafc8.png">

Would you be able to offer a possible explanation why this may be so?

Merci beaucoup toujours!

**Comment by chrisamanse** [comment]
This is because of the sample bundles listed in [LIKHABundles.plist](https://github.com/usbong/LIKHA/blob/master/LIKHA/LIKHABundles.plist#L5-L13).

**Comment by masarapmabuhay** [comment]
D'accord! L'outil, c'est trés bien! Merci beaucoup, vraiment!
