### ISSUE TITLE
Cover Image should also include the background image

### ISSUE THREAD

**Issue by masarapmabuhay** [chrisamanse/LIKHA-Guide#9]
Salut! After running the successfully built LIKHA on a simulator, I learned that I'll need to include the background image as well. I was under the impression that the app would automatically get the background image in the .utree. Apparently, it doesn't. Nonetheless, hakuna matata!

**Comment by chrisamanse** [comment]
Yes, the background image also needs to be provided because the `.utree` is compressed and it will take too long to decompress it and fetch the background image. Providing the background image will avoid this step, and only pressing the Start button will the app decompress the file.

**Comment by masarapmabuhay** [comment]
D'accord! Merci beaucoup!
